# -*- coding: utf-8 -*-
"""Outlier_Treatment .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HTJZjb231HGVewhMJ7dzaXqF8Zx5BpKF
"""

#outlier are extreme value

import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

salary = [11,22,44,55,123,65,76,35,74,8,647,34,23,56,86,84,34,23,456,567,64,34,234,64,56,25,250,140,36,76,35,67,53,46,97,75]

salary

#fiv point summary

#min, 25th, 50th percentile ,75th , 100th

np.quantile(salary,[0,0.25,0.50,0.75,1])

df = pd.DataFrame(salary,columns=['salary'])

df

df.describe()

plt.figure(figsize =(12,5))
plt.subplot(1,2,1)
sns.histplot(df['salary'],kde =True)
plt.title("Dist Plot")

plt.subplot(1,2,2)
sns.boxplot(data=df, x='salary')
plt.title("Box plot")
plt.show()

#here the distribution is nor skewed as the outliers are present on both side
# in box plot , we see there are outliers
#dropping the outlier
#capping the outlier
#replace with mean and median

#droping the outlier
Q1 =df['salary'].quantile(0.25)
Q3 =df['salary'].quantile(0.75)
IQR = Q3-Q1
lower_fence = Q1-1.5*IQR
upper_fence = Q3+1.5*IQR

df_filtered =df[(df.salary>=lower_fence)&(df.salary <= upper_fence)]

df.shape

df_filtered.shape

plt.figure(figsize =(12,5))
plt.subplot(1,2,1)
sns.histplot(df_filtered['salary'],kde =True)
plt.title("Dist Plot")

plt.subplot(1,2,2)
sns.boxplot(data=df_filtered, x='salary')
plt.title("Box plot")
plt.show()

#imputation with mean and median
df['salary_imputed_mean'] = np.where((df.salary>=upper_fence) | (df.salary<=lower_fence),df['salary'].mean() ,df['salary'])

df

plt.figure(figsize =(12,5))
plt.subplot(1,2,1)
sns.histplot(df['salary_imputed_mean'],kde =True)
plt.title("Dist Plot")

plt.subplot(1,2,2)
sns.boxplot(data=df, x='salary_imputed_mean')
plt.title("Box plot")
plt.show()

#CAPPING the outlier

#Replacing the nearest value which is not outlier

df

lower_cap = df['salary'].quantile(0.05) #lower cao is 5th percentile

upper_cap =  df['salary'].quantile(0.95) #upper cap is 95th percentile

lower_cap

upper_cap

#this cap value is nearest to lower fence and upper fence

#replace outlier with cap

df["salary_capped"] = np.where(
    df["salary"] < lower_cap,
    lower_cap,
    np.where(
        df["salary"] > upper_cap,
        upper_cap,
        df["salary"]
    )
)

df

